# Generated by Django 4.1.5 on 2023-01-17 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='создана')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='последние изменение')),
            ],
            options={
                'verbose_name': 'предмет из корзины',
                'verbose_name_plural': 'предметы из корзины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='фамилия')),
                ('city', models.CharField(max_length=64, verbose_name='город')),
                ('street', models.CharField(max_length=64, verbose_name='улица')),
                ('house', models.CharField(max_length=32, verbose_name='дом')),
                ('building', models.CharField(max_length=32, verbose_name='корпус')),
                ('apartment', models.CharField(max_length=32, verbose_name='квартира')),
                ('phone', models.CharField(max_length=32, verbose_name='телефон')),
                ('email', models.CharField(max_length=64, verbose_name='почта')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('promo_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='использованный промокод')),
                ('real_price', models.IntegerField(verbose_name='итог без скидки')),
                ('total_price', models.IntegerField(verbose_name='итог')),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='скидка (%)')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=20, verbose_name='промокод')),
                ('discount', models.PositiveSmallIntegerField(default=15, verbose_name='скидка (%)')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order', verbose_name='заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
