# Generated by Django 4.1.5 on 2023-01-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_comments_comment_to_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='можете оставить поле пустым', max_length=200, unique=True, verbose_name='заголовок на англ.'),
        ),
    ]
