# Generated by Django 4.1.5 on 2023-01-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_description_customuser_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='user_images', verbose_name='аватарка'),
        ),
    ]
