# Generated by Django 4.1.5 on 2023-01-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='user_images/default.png', upload_to='user_images', verbose_name='аватарка'),
        ),
    ]
