# Generated by Django 4.1.5 on 2023-01-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comments',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='количество комментариевпод постами пользователя', verbose_name='комментариев'),
        ),
    ]
